SELECT 
    [Month],
    [VISN],
    [Commentary - Initiatives],
    [Commentary - Executive Level Commentary],
    [Category],
    [Value],
    [Direct/Community],
    [Appropriation],
    [GP_SP],
    [CostDriver],
    [CollectionsReimbursables],
    [MCCF],
    [YTD Allocated],
    [Obligation YTD],
    [Obligation YTD_Cost_Drivers], 
    [Obligation PYTD],
    [Plan],
    [Surplus/Need],
    [Projection],
    [Expected],
    [Amount YTD],
    [Medical Services],
    [Support & Compliance],
    [Facilities],
    [Medical Community Care]
FROM [VHA104_Finance].[CDR].[FLR_VISN_Input_Main]

UNION ALL

SELECT 
    [Month],
    [VISN],
    NULL AS [Commentary - Initiatives],
    NULL AS [Commentary - Executive Level Commentary],
    NULL AS [Category],
    NULL AS [Value],
    [Direct/Community],
    [Appropriation],
    [GP_SP],
    [CostDriver],
    NULL AS [CollectionsReimbursables],
    NULL AS [MCCF],
    [YTD Allocated],
    [Obligation YTD],
    NULL AS [Obligation YTD_Cost_Drivers], 
    NULL AS [Obligation PYTD],
    [Plan],
    [Surplus/Need],
    NULL AS [Projection],
    NULL AS [Expected],
    NULL AS [Amount YTD],
    [Medical Services],
    [Support & Compliance],
    [Facilities],
    [Medical Community Care]
FROM [VHA104_Finance].[CDR].[FLR_VISN_Input_SP];
