SELECT 
    Month,
    VISN,
    REPLACE([Commentary - Initiatives], '|', CHAR(10)) AS [Commentary - Initiatives],
    [Commentary - Executive Level Commentary],
    Category,
    Value / 1000 AS Value,
    [Direct/Community],
    Appropriation,
    GP_SP,
    CostDriver,
    CollectionsReimbursables,
    MCCF,
    [YTD Allocated] / 1000 AS [YTD Allocated],
    [Obligation YTD] / 1000 AS [Obligation YTD],
    [Obligation YTD_Cost_Drivers] / 1000 AS [Obligation YTD_Cost_Drivers],
    [Obligation PYTD] / 1000 AS [Obligation PYTD],
    [Plan] / 1000 AS [Plan],
    [Surplus/Need] / 1000 AS [Surplus/Need],
    [Projection] / 1000 AS [Projection],
    [Expected] / 1000 AS [Expected],
    [Amount YTD] / 1000 AS [Amount YTD],
    [Medical Services] / 1000 AS [Medical Services],
    [Support & Compliance] / 1000 AS [Support & Compliance],
    [Facilities] / 1000 AS [Facilities],
    [Medical Community Care] / 1000 AS [Medical Community Care]
FROM [VHA104_Finance].[CDR].[FLR_VISN_Input_Main]

UNION ALL

SELECT 
    Month,
    VISN,
    NULL AS [Commentary - Initiatives],
    NULL AS [Commentary - Executive Level Commentary],
    NULL AS Category,
    NULL AS Value,
    [Direct/Community],
    [Appropriation],
    [GP_SP],
    [CostDriver],
    NULL AS [CollectionsReimbursables],
    NULL AS [MCCF],
    [YTD Allocated] / 1000 AS [YTD Allocated],
    [Obligation YTD] / 1000 AS [Obligation YTD],
    NULL AS [Obligation YTD_Cost_Drivers], 
    NULL AS [Obligation PYTD],
    [Plan] / 1000 AS [Plan],
    [Surplus/Need] / 1000 AS [Surplus/Need],
    NULL AS [Projection],
    NULL AS [Expected],
    NULL AS [Amount YTD],
    [Medical Services] / 1000 AS [Medical Services],
    [Support & Compliance] / 1000 AS [Support & Compliance],
    [Facilities] / 1000 AS [Facilities],
    [Medical Community Care] / 1000 AS [Medical Community Care]
FROM [VHA104_Finance].[CDR].[FLR_VISN_Input_SP];
