CREATE TABLE [VHA104_Finance].[App].[VISN_Input_Main] (
    Month DATE,
    VISN INT,
    [Direct Care - YTDAllocationsVERA] DECIMAL(18, 6),
    [Direct Care - Collections - Projection] DECIMAL(18, 6),
    [Direct Care - Collections - Expected] DECIMAL(18, 6),
    [Direct Care - Collections - AmountYTD] DECIMAL(18, 6),
    [Direct Care - Reimbursables - Projection] DECIMAL(18, 6),
    [Direct Care - Reimbursables - Expected] DECIMAL(18, 6),
    [Direct Care - Reimbursables - AmountYTD] DECIMAL(18, 6),
    [Direct Care - Personal Services - Plan] DECIMAL(18, 6),
    [Direct Care - Personal Services - ObligationsYTD] DECIMAL(18, 6),
    [Direct Care - Personal Services - GrowthYTD] DECIMAL(18, 6),
    [Direct Care - Pharmacy (2631, 2636) - Plan] DECIMAL(18, 6),
    [Direct Care - Pharmacy (2631, 2636) - ObligationsYTD] DECIMAL(18, 6),
    [Direct Care - Pharmacy (2631, 2636) - GrowthYTD] DECIMAL(18, 6),
    [Direct Care - Pharmacy (CMOP) - Plan] DECIMAL(18, 6),
    [Direct Care - Pharmacy (CMOP) - ObligationsYTD] DECIMAL(18, 6),
    [Direct Care - Contracts - Plan] DECIMAL(18, 6),
    [Direct Care - Contracts - ObligationsYTD] DECIMAL(18, 6),
    [Direct Care - Contracts - GrowthYTD] DECIMAL(18, 6),
    [Direct Care - All Other - Plan] DECIMAL(18, 6),
    [Direct Care - TotalGP - ObligationsYTD] DECIMAL(18, 6),
    [Direct Care - TotalGP - GrowthYTD] DECIMAL(18, 6),
    [Community Care - YTDAllocationsVERA] DECIMAL(18, 6),
    [Community Care - MCCF - Projection] DECIMAL(18, 6),
    [Community Care - MCCF - Expected] DECIMAL(18, 6),
    [Community Care - MCCF - AmountYTD] DECIMAL(18, 6),
    [Community Care - TotalGP - Plan] DECIMAL(18, 6),
    [Community Care - TotalGP - ObligationsYTD] DECIMAL(18, 6),
    [Community Care - Outpatient - ObligationsYTD] DECIMAL(18, 6),
    [Community Care - Inpatient - ObligationsYTD] DECIMAL(18, 6),
    [Community Care - Dental - ObligationsYTD] DECIMAL(18, 6),
    [Total Surplus/Need - CurrentGP - SupportCompliance] DECIMAL(18, 6),
    [Total Surplus/Need - CurrentGP - Medical Services] DECIMAL(18, 6),
    [Total Surplus/Need - CurrentGP - Facilities] DECIMAL(18, 6),
    [Total Surplus/Need - CurrentSP - Medical Services] DECIMAL(18, 6),
    [Total Surplus/Need - CurrentSP - SupportCompliance] DECIMAL(18, 6),
    [Total Surplus/Need - CurrentSP - Facilities] DECIMAL(18, 6),
    [Commentary - Initiatives] TEXT,
    [Commentary - Executive Level Commentary] TEXT,
    [Direct Care - All Other - ObligationsYTD] DECIMAL(18, 6),
    [Community Care - TotalGP - GrowthYTD] DECIMAL(18, 6),
    [Direct Care - Pharmacy (CMOP) - GrowthYTD] DECIMAL(18, 6),
    [Direct Care - All Other - GrowthYTD] DECIMAL(18, 6),
    [Community Care - Outpatient - ObligationsPYTD] DECIMAL(18, 6),
    [Community Care - Inpatient - ObligationsPYTD] DECIMAL(18, 6),
    [Community Care - Dental - ObligationsPYTD] DECIMAL(18, 6),
    [Community Care - All Other - ObligationsPYTD] DECIMAL(18, 6),
    [Community Care - All Other - ObligationsYTD] DECIMAL(18, 6),
    TestRecord TEXT,
    Status NVARCHAR(250)
);
